[build]
builder = "nixpacks"

[deploy]
startCommand = "daphne patient_vitals_backend.asgi:application --bind 0.0.0.0 --port $PORT"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3