# Generated by Django 5.2.5 on 2025-09-02 13:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Unique patient ID, e.g., PT-2024-001', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('room', models.CharField(help_text='Room number, e.g., ICU-12', max_length=50)),
                ('condition', models.TextField(help_text="Patient's medical condition or monitoring reason")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='ESP32 device ID or MAC address', max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='patient_vitals_api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Start of the aggregation period')),
                ('end_time', models.DateTimeField(help_text='End of the aggregation period')),
                ('avg_heart_rate', models.FloatField(blank=True, null=True)),
                ('avg_spo2', models.FloatField(blank=True, null=True)),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('avg_accel_x', models.FloatField(blank=True, null=True)),
                ('avg_accel_y', models.FloatField(blank=True, null=True)),
                ('avg_accel_z', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], default='low', max_length=20)),
                ('confidence', models.FloatField(blank=True, help_text='ML confidence score, e.g., 0.94', null=True)),
                ('summary', models.TextField(help_text='LLM-generated summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='patient_vitals_api.patient')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.FloatField(blank=True, help_text='Heart rate in BPM', null=True)),
                ('spo2', models.FloatField(blank=True, help_text='SpO2 percentage', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Body temperature in °F', null=True)),
                ('ecg_data', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='ECG waveform samples', null=True, size=None)),
                ('accel_x', models.FloatField(blank=True, null=True)),
                ('accel_y', models.FloatField(blank=True, null=True)),
                ('accel_z', models.FloatField(blank=True, null=True)),
                ('motion_status', models.CharField(blank=True, help_text="e.g., 'Normal Activity'", max_length=50, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patient_vitals_api.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
