# Generated by Django 5.2.5 on 2025-09-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_vitals_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='summary',
            field=models.CharField(default='default', help_text='Summary of medical condition e.g Cardiac Monitoring', max_length=50),
            preserve_default=False,
        ),
    ]
