# Generated by Django 5.2.5 on 2025-09-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_vitals_api', '0002_patient_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='summary',
        ),
    ]
