# Generated by Django 5.2.5 on 2025-09-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_vitals_api', '0003_remove_patient_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vital',
            name='ecg_data',
        ),
        migrations.AddField(
            model_name='vital',
            name='ecg',
            field=models.IntegerField(blank=True, help_text='ECG waveform samples', null=True),
        ),
        migrations.AlterField(
            model_name='vital',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='Heart rate in BPM', null=True),
        ),
        migrations.AlterField(
            model_name='vital',
            name='spo2',
            field=models.IntegerField(blank=True, help_text='SpO2 percentage', null=True),
        ),
    ]
