# Generated by Django 5.2.5 on 2025-09-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_vitals_api', '0004_remove_vital_ecg_data_vital_ecg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vital',
            name='ecg',
            field=models.FloatField(blank=True, help_text='ECG waveform samples', null=True),
        ),
    ]
