# Generated by Django 5.2.5 on 2025-09-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_vitals_api', '0005_alter_vital_ecg'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.FloatField(default=50.4, help_text='Height in metres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.FloatField(default=1.4, help_text='Weight in kilogram'),
            preserve_default=False,
        ),
    ]
