# Generated by Django 5.2.5 on 2025-09-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_vitals_api', '0006_patient_height_patient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vital',
            name='resp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vital',
            name='systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
