# Generated by Django 5.2.5 on 2025-09-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_vitals_api', '0007_vital_diastolic_vital_resp_vital_systolic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', help_text='Gender: Male or Female'),
            preserve_default=False,
        ),
    ]
