# Generated by Django 5.2.5 on 2025-09-05 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_vitals_api', '0008_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient_vitals_api.patient'),
            preserve_default=False,
        ),
    ]
