# Generated by Django 5.2.5 on 2025-09-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_vitals_api', '0009_vital_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregate',
            name='confidence',
            field=models.FloatField(blank=True, default=0, help_text='ML confidence score, e.g., 0.94', null=True),
        ),
        migrations.AlterField(
            model_name='aggregate',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], default='N/A', max_length=20),
        ),
    ]
